import type { Metadata } from "next";
import { ThemeProvider } from "@/providers/theme.provider";
import { UserStoreProvider } from "@/providers/stores/user-store.provider";
import { Providers } from "@/providers/providers.provider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`h-dvh overflow-y-scroll w-full antialiased`}>
        <Providers>
          <UserStoreProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="dark"
              enableSystem={false}
            >
              {children}
            </ThemeProvider>
          </UserStoreProvider>
        </Providers>
      </body>
    </html>
  );
}
